### ISSUE TITLE
Update the ring crate to 0.17

### ISSUE THREAD

**Issue by maoe** [suransea/jwt-rust#4]
Currently jwts depends on ring 0.16.20, which was released more than 3 years ago. ring 0.17 was then released 7 months ago and popular projects like rustls have switched to 0.17. Maybe it's a good time to switch to 0.17 in jwts too.

Looking at the code briefly there's at least one obstacle to solve: `ring::error::KeyRejected` no longer provides `&'static str` as a description of the error. So it'd need a breaking change at least unless we request the upstream to provide it.

What do you think?

**Comment by suransea** [comment]
I prefer to use aws-lc-rs since rustls defaults to it, but it will bring more breaking changes. Fortunately, it is feasible because few people use this library.

**Comment by maoe** [comment]
The latest version of jwts with aws-lc-rs worked for me. Thanks!
